### PR TITLE
Make package pip installable and update notebook

### LINKED ISSUE #1: Make code pip installable
Hi, I think your notebook is really interesting! Would you be willing to accept a PR that makes the code in this repository pip installable so it's easier for others to reuse?

I've made PRs on lots of repositories with scientific code, and will do my best to explain what I did so you can learn something

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #1 

This PR does the following:

1. Applies the standard Python `src/` layout to the repository (aka move all code into a folder called `src`)
2. Switches the name to use standard Python snake case
3. Add a `setup.cfg` and `setup.py` that has the information on where the code is and how it should be installed
4. Add installation instructions to the README
5. Update the data preprocessing script to use tqdm and put inside package to be used with `python -m automated_series_classification.dataprep`
6. Update the main notebook to make sure everything still runs properly, but it wasn't possible to test since the original data is not available and the preprocesing of the Bradley dataset is not reproducible because it relies on ``arthor`` which is not available as far as I know

### CODE REVIEW

**Comment by cthoyt** [comment]
@iwatobipen I'll put it back as "draft" and mark for review/let you know when it's ready for you to take a look!

**Comment by iwatobipen** [comment]
Sure, I'll review the code.
And I have a request. Could you please add you as author?
Thanks,

**Comment by cthoyt** [comment]
I was able to find the Bradley dataset and download it, but it looks like there's Novartis-internal code called `arthor` that's required to generate the input (somewhere I wrote this was Novartis code, but I guess that it's from NextMove). I also copied in the DataPreprocessing.ipynb notebook into this repo, but it's not so useful.

Because of this, I was ultimately not able to re-run the notebook (though everything does import correctly)

Now it should be ready for review

**Comment by cthoyt** [comment]
One question - this code you copied from the original article and you aren't one of the authors, right? I'm a bit worried about the licensing implications.

Anyway, how did you want me to add myself as an author? Just mark on the readme?

**Comment by iwatobipen** [comment]
> One question - this code you copied from the original article and you aren't one of the authors, right? I'm a bit worried about the licensing implications.
> 
> Anyway, how did you want me to add myself as an author? Just mark on the readme?

You are right. The author of the original code is krugefr1. I'm not the author.

**Pull request merged**
