### PR TITLE
Get arthor working again

### PR DESCRIPTION
**Pull request by greglandrum**
Changes here:
- make sure everything still works with arthor (I tried this with my local copy of arthor)
- add a notebook showing how to use arthor
- removed the ChEMBL targets notebook and data since that didn't seem super useful. I may clean this up and add it back again later

Please take a look at the changes and see what you think!

### CODE REVIEW

**Comment by greglandrum** [comment]
@iwatobipen how would you feel about moving this repo to the RDKit organization?

**Comment by iwatobipen** [comment]
> @iwatobipen how would you feel about moving this repo to the RDKit organization?
That's cool!
I will be happy if I can move the repo to the RDKit organization!

**Comment by greglandrum** [comment]
> > @iwatobipen how would you feel about moving this repo to the RDKit organization?
> That's cool!
> I will be happy if I can move the repo to the RDKit organization!

Great. Here are instructions for doing the transfer: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by iwatobipen** [comment]
Thanks! I'll do it ;)

**Pull request merged**
